name: Update README with datetime
# on:
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README.md
        run: |
          echo "Last updated at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > README.md
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README [skip ci]" || echo "No changes"
          git push
          

